#!/usr/bin/env python3
"""Enhanced scheduler - orchestrates the enhanced paper pipeline."""

import sys
import json
import smtplib
from pathlib import Path
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

sys.path.insert(0, str(Path(__file__).parent))

from enhanced_crawler import crawl_all
from enhanced_report import generate_report
from reproducer import generate_repro_summary

DATA_DIR = Path("/root/git/mimo/paper-pipeline/data")
REPORTS_DIR = Path("/root/git/mimo/paper-pipeline/reports")

SMTP_HOST = "smtp.163.com"
SMTP_PORT = 465
SENDER = "cl0udp1k@163.com"
AUTH_CODE = "CKnX5kKGxzU3VkVT"
RECIPIENT = "cl0udp1k@163.com"


def markdown_to_html(md_text):
    """Convert markdown to styled HTML."""
    lines = md_text.split("\n")
    html_parts = []
    in_table = False
    in_code = False
    
    for line in lines:
        # Code blocks
        if line.startswith("```"):
            if in_code:
                html_parts.append("</code></pre>")
                in_code = False
            else:
                lang = line[3:].strip()
                html_parts.append(f'<pre class="code-block"><code data-lang="{lang}">')
                in_code = True
            continue
        
        if in_code:
            html_parts.append(line.replace("<", "&lt;").replace(">", "&gt;"))
            continue
        
        # Headers
        if line.startswith("# "):
            html_parts.append(f'<h1 class="title">{line[2:]}</h1>')
        elif line.startswith("## "):
            html_parts.append(f'<h2 class="section">{line[3:]}</h2>')
        elif line.startswith("### "):
            html_parts.append(f'<h3 class="subsection">{line[4:]}</h3>')
        # Table rows
        elif line.startswith("|"):
            if not in_table:
                html_parts.append('<table class="data-table">')
                in_table = True
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if all(set(c) <= set("-| ") for c in cells):
                continue  # skip separator
            tag = "th" if not in_table else "td"
            row = "".join(f"<{tag}>{c}</{tag}>" for c in cells)
            html_parts.append(f"<tr>{row}</tr>")
        else:
            if in_table:
                html_parts.append("</table>")
                in_table = False
            # Blockquote
            if line.startswith("> "):
                html_parts.append(f'<blockquote>{line[2:]}</blockquote>')
            # List items
            elif line.startswith("- "):
                html_parts.append(f'<li>{line[2:]}</li>')
            # Horizontal rule
            elif line.startswith("---"):
                html_parts.append("<hr>")
            # Regular text
            elif line.strip():
                # Bold
                import re
                line = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)
                # Links
                line = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', line)
                html_parts.append(f"<p>{line}</p>")
    
    if in_table:
        html_parts.append("</table>")
    
    return "\n".join(html_parts)


def build_html_email(summary_text, report_html, date_str):
    """Build a beautifully styled HTML email."""
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f0f2f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:700px;margin:0 auto;padding:20px;">

<!-- Header -->
<div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);border-radius:12px 12px 0 0;padding:30px;text-align:center;">
  <h1 style="color:#fff;margin:0;font-size:24px;">📚 AI 论文日报</h1>
  <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:14px;">{date_str} · 自动抓取 · 含引用数据</p>
</div>

<!-- Summary Card -->
<div style="background:#fff;padding:24px;border-bottom:1px solid #eee;">
  <h2 style="color:#1a1a2e;margin:0 0 12px;font-size:18px;">📋 今日摘要</h2>
  <div style="color:#555;line-height:1.8;font-size:14px;">
    {summary_text}
  </div>
</div>

<!-- Main Content -->
<div style="background:#fff;padding:24px;">
  {report_html}
</div>

<!-- Footer -->
<div style="background:#fafafa;padding:16px 24px;border-radius:0 0 12px 12px;text-align:center;border-top:1px solid #eee;">
  <p style="color:#999;margin:0;font-size:12px;">
    Generated by Paper Pipeline · <a href="https://arxiv.org" style="color:#667eea;">arXiv</a> + <a href="https://www.semanticscholar.org" style="color:#667eea;">Semantic Scholar</a>
  </p>
</div>

</div>
</body>
</html>"""


def build_summary_html(papers):
    """Build a summary section from papers list."""
    by_topic = {}
    for p in papers:
        t = p.get("topic", "Other")
        by_topic.setdefault(t, []).append(p)
    
    stats = " · ".join(f"{t}: {len(ps)}篇" for t, ps in by_topic.items())
    
    top5 = ""
    for i, p in enumerate(papers[:5], 1):
        title = p.get("title", "N/A")[:60]
        cites = p.get("citation_count", 0) or 0
        url = p.get("url", f"https://arxiv.org/abs/{p.get('id', '')}")
        top5 += f"""<tr>
          <td style="padding:8px;border-bottom:1px solid #eee;color:#667eea;font-weight:bold;">#{i}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;"><a href="{url}" style="color:#0f3460;text-decoration:none;">{title}</a></td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;color:#e94560;font-weight:bold;">{cites}</td>
        </tr>"""
    
    return f"""
    <p><strong>总计:</strong> {len(papers)} 篇论文 | {stats}</p>
    <table style="width:100%;border-collapse:collapse;margin-top:12px;">
      <tr style="background:#f8f9fa;">
        <th style="padding:8px;text-align:left;border-bottom:2px solid #ddd;">#</th>
        <th style="padding:8px;text-align:left;border-bottom:2px solid #ddd;">标题</th>
        <th style="padding:8px;text-align:center;border-bottom:2px solid #ddd;">引用</th>
      </tr>
      {top5}
    </table>
    """


def send_email(subject, plain_body, html_body=None, attachments=None):
    """Send email via 163 SMTP with optional attachments."""
    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = SENDER
    msg["To"] = RECIPIENT
    
    # HTML alternative part
    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(plain_body, "plain", "utf-8"))
    if html_body:
        alt.attach(MIMEText(html_body, "html", "utf-8"))
    msg.attach(alt)
    
    # Attachments
    if attachments:
        for filepath in attachments:
            filepath = Path(filepath)
            if filepath.exists():
                with open(filepath, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header("Content-Disposition", f'attachment; filename="{filepath.name}"')
                    msg.attach(part)
    
    with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
        server.login(SENDER, AUTH_CODE)
        server.sendmail(SENDER, RECIPIENT, msg.as_string())
    print(f"Email sent: {subject}")


def daily_run():
    """Run enhanced daily pipeline."""
    today = datetime.now().strftime("%Y-%m-%d")
    print(f"\n{'='*60}")
    print(f"Enhanced Paper Pipeline: {today}")
    print(f"{'='*60}\n")
    
    # Step 1: Crawl with Semantic Scholar enrichment
    print("[1/4] Crawling papers with citation data...")
    papers = crawl_all()
    
    if not papers:
        print("No papers found.")
        return
    
    # Step 2: Generate enhanced report
    print("\n[2/4] Generating enhanced report...")
    report_path = generate_report(papers, today)
    
    # Step 3: Generate repro guides
    print("\n[3/4] Generating reproduction guides...")
    repro_summary, _ = generate_repro_summary(papers[:5])
    
    # Step 4: Send email with styled HTML + attachments
    print("\n[4/4] Sending email briefing...")
    report_md = report_path.read_text("utf-8")
    repro_md = repro_summary.read_text("utf-8") if repro_summary.exists() else ""
    
    full_plain = f"{report_md}\n\n---\n\n{repro_md}"
    report_html = markdown_to_html(report_md)
    repro_html = markdown_to_html(repro_md)
    summary_html = build_summary_html(papers)
    html_body = build_html_email(summary_html, report_html + "<hr>" + repro_html, today)
    
    # Attachments: report .md + repro summary .md
    attachments = [report_path]
    if repro_summary.exists():
        attachments.append(repro_summary)
    
    send_email(f"📚 AI论文日报 {today}", full_plain, html_body, attachments)
    
    print(f"\n{'='*60}")
    print(f"Done! {len(papers)} papers processed with citation data.")
    print(f"{'='*60}\n")


def weekly_summary():
    """Send weekly summary."""
    today = datetime.now().strftime("%Y-%m-%d")
    reports = sorted(REPORTS_DIR.glob("daily_enhanced_*.md"))[-7:]
    
    weekly = f"# AI论文周报 {today}\n\n"
    total = 0
    for r in reports:
        content = r.read_text("utf-8")
        weekly += f"\n---\n\n{content}\n"
        total += content.count("| ") // 5  # rough count
    
    send_email(f"📚 AI论文周报 {today}", weekly)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "daily"
    if cmd == "daily":
        daily_run()
    elif cmd == "weekly":
        weekly_summary()
