#!/usr/bin/env python3
"""Enhanced report generator with citation data and analysis."""

import json
from pathlib import Path
from datetime import datetime

DATA_DIR = Path("/root/git/mimo/paper-pipeline/data")
REPORTS_DIR = Path("/root/git/mimo/paper-pipeline/reports")


def generate_report(papers, today=None):
    """Generate enhanced daily report with citation data."""
    if today is None:
        today = datetime.now().strftime("%Y-%m-%d")
    
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    
    # Group by topic
    by_topic = {}
    for p in papers:
        topic = p.get("topic", "Unknown")
        by_topic.setdefault(topic, []).append(p)
    
    report = f"""# AI 论文日报 {today}

> 自动抓取 · {len(papers)} 篇论文 · 覆盖 {len(by_topic)} 个领域

---

## Top 5 候选复现论文（按引用+时效排序）

"""
    
    for i, p in enumerate(papers[:5], 1):
        citations = p.get("citation_count", 0) or 0
        tldr = p.get("tldr", "N/A")
        report += f"""### #{i} {p.get('title', 'N/A')}

| 字段 | 值 |
|------|-----|
| **领域** | {p.get('topic', 'N/A')} |
| **ArXiv** | [{p.get('id', 'N/A')}]({p.get('url', '')}) |
| **日期** | {p.get('published', 'N/A')[:10]} |
| **作者** | {', '.join(p.get('authors', [])[:3])} |
| **引用数** | {citations} |
| **AI摘要** | {tldr[:200] if tldr else 'N/A'} |

"""
    
    report += "---\n\n## 分领域论文统计\n\n"
    report += "| 领域 | 数量 | 最高引用 |\n"
    report += "|------|------|----------|\n"
    
    for topic, topic_papers in by_topic.items():
        max_cites = max((p.get("citation_count", 0) or 0) for p in topic_papers)
        report += f"| {topic} | {len(topic_papers)} | {max_cites} |\n"
    
    report += "\n---\n\n## 全部论文列表\n\n"
    report += "| # | 领域 | 标题 | 日期 | 引用 | ArXiv |\n"
    report += "|---|------|------|------|------|-------|\n"
    
    for i, p in enumerate(papers, 1):
        title = p.get("title", "N/A")[:55]
        if len(p.get("title", "")) > 55:
            title += "..."
        cites = p.get("citation_count", 0) or 0
        report += f"| {i} | {p.get('topic', 'N/A')} | {title} | {p.get('published', 'N/A')[:10]} | {cites} | [{p.get('id', 'N/A')}]({p.get('url', '')}) |\n"
    
    report += f"""

---

## 复现优先级

基于引用数和时效性的综合评分，Top 5 论文建议优先复现：

"""
    for i, p in enumerate(papers[:5], 1):
        report += f"{i}. **{p.get('title', 'N/A')[:60]}** — {p.get('topic', 'N/A')} ({p.get('citation_count', 0) or 0} citations)\n"
    
    report += f"""

---
*Generated by Enhanced Paper Pipeline on {today}*
"""
    
    report_path = REPORTS_DIR / f"daily_enhanced_{today}.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"Enhanced report: {report_path}")
    return report_path


if __name__ == "__main__":
    import sys
    today = sys.argv[1] if len(sys.argv) > 1 else datetime.now().strftime("%Y-%m-%d")
    papers_file = DATA_DIR / today / "papers_enhanced.json"
    
    if papers_file.exists():
        papers = json.loads(papers_file.read_text())
        generate_report(papers, today)
    else:
        print(f"No enhanced papers for {today}. Run enhanced_crawler.py first.")
