#!/usr/bin/env python3
"""Paper analyzer - interpret papers and generate summaries."""

import json
from pathlib import Path
from datetime import datetime

DATA_DIR = Path("/root/git/mimo/paper-pipeline/data")
REPORTS_DIR = Path("/root/git/mimo/paper-pipeline/reports")


def generate_paper_summary(paper):
    """Generate structured summary for a single paper."""
    topic_name, p = paper
    
    summary = f"""## {p['title']}

**领域**: {topic_name}  
**ArXiv**: {p['arxiv_id']}  
**日期**: {p['published']}  
**作者**: {', '.join(p['authors'][:5])}{'...' if len(p['authors']) > 5 else ''}  
**链接**: {p['url']}

### 摘要
{p['abstract'][:500]}{'...' if len(p['abstract']) > 500 else ''}

### 关键点
- **问题**: {extract_problem(p['abstract'])}
- **方法**: {extract_method(p['abstract'])}
- **结果**: {extract_result(p['abstract'])}
- **意义**: {extract_significance(p['abstract'], topic_name)}
"""
    return summary


def extract_problem(abstract):
    """Extract the main problem from abstract."""
    sentences = abstract.split(". ")
    for s in sentences:
        if any(kw in s.lower() for kw in ["challenge", "problem", "limitation", "bottleneck", "issue", "difficulty"]):
            return s.strip()[:150]
    return sentences[0].strip()[:150] if sentences else "N/A"


def extract_method(abstract):
    """Extract the method from abstract."""
    sentences = abstract.split(". ")
    for s in sentences:
        if any(kw in s.lower() for kw in ["propose", "introduce", "present", "develop", "method", "framework", "approach", "algorithm"]):
            return s.strip()[:150]
    return sentences[1].strip()[:150] if len(sentences) > 1 else "N/A"


def extract_result(abstract):
    """Extract results from abstract."""
    sentences = abstract.split(". ")
    for s in sentences:
        if any(kw in s.lower() for kw in ["achieve", "result", "outperform", "improve", "state-of-the-art", "sota", "accuracy", "gain"]):
            return s.strip()[:150]
    return "N/A"


def extract_significance(abstract, topic):
    """Extract significance in context of the topic."""
    if "agent" in topic.lower():
        kw = ["agent", "tool", "reasoning", "planning", "autonomous"]
    elif "inference" in topic.lower():
        kw = ["speed", "latency", "throughput", "efficiency", "memory", "cache"]
    elif "multimodal" in topic.lower():
        kw = ["visual", "image", "video", "cross-modal", "alignment"]
    elif "code" in topic.lower():
        kw = ["code", "program", "generation", "repair", "benchmark"]
    else:
        kw = ["novel", "contribution", "advance"]
    
    sentences = abstract.split(". ")
    for s in sentences:
        if any(k in s.lower() for k in kw):
            return s.strip()[:150]
    return "N/A"


def generate_daily_report(papers, today=None):
    """Generate daily report with all papers."""
    if today is None:
        today = datetime.now().strftime("%Y-%m-%d")
    
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    
    report = f"""# AI 论文日报 {today}

> 自动抓取 · {len(papers)} 篇论文 · 覆盖 AI Agent / LLM推理 / 多模态 / 代码生成

---

## Top 5 候选复现论文

"""
    
    # Top 5 with detailed analysis
    for i, paper in enumerate(papers[:5], 1):
        topic_name, p = paper
        report += f"### #{i} [{topic_name}] {p['title']}\n"
        report += f"- **ArXiv**: [{p['arxiv_id']}]({p['url']})\n"
        report += f"- **日期**: {p['published']} | **作者**: {', '.join(p['authors'][:3])}\n"
        report += f"- **复现难度**: {'⭐' * min(len(p['authors']), 5)}\n"
        report += f"- **复现价值**: {'🔥' * min(int(p.get('total_score', 50) / 20), 5)}\n"
        report += f"- **摘要**: {p['abstract'][:200]}...\n\n"
    
    report += "---\n\n## 全部论文列表\n\n"
    report += "| # | 领域 | 标题 | 日期 | ArXiv |\n"
    report += "|---|------|------|------|-------|\n"
    
    for i, (topic, p) in enumerate(papers, 1):
        title_short = p['title'][:60] + ('...' if len(p['title']) > 60 else '')
        report += f"| {i} | {topic} | {title_short} | {p['published']} | [{p['arxiv_id']}]({p['url']}) |\n"
    
    report += f"""
---

## 统计
- 总论文数: {len(papers)}
- AI Agent: {sum(1 for t, _ in papers if t == 'AI Agent')}
- LLM推理优化: {sum(1 for t, _ in papers if t == 'LLM推理优化')}
- 多模态大模型: {sum(1 for t, _ in papers if t == '多模态大模型')}
- 代码生成: {sum(1 for t, _ in papers if t == '代码生成')}

---
*Generated by Paper Pipeline on {today}*
"""
    
    report_path = REPORTS_DIR / f"daily_{today}.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"Report saved: {report_path}")
    return report_path


if __name__ == "__main__":
    import sys
    today = sys.argv[1] if len(sys.argv) > 1 else datetime.now().strftime("%Y-%m-%d")
    papers_file = DATA_DIR / today / "papers.json"
    
    if papers_file.exists():
        papers = json.loads(papers_file.read_text())
        generate_daily_report(papers, today)
    else:
        print(f"No papers found for {today}. Run paper_crawler.py first.")
